#!/bin/sh

# Script to do stuff as part of sway startup. This is mostly here because
# you can't do conditionals in sway config

export LOCK_SEC=300
swayidle -w \
	timeout "$LOCK_SEC" 'swaylock -f' \
	# dpms off has been disabled because it causes the laptop to go to sleep
	# timeout "$LOCK_SEC" 'swaymsg "output * dpms off"' \
	# 	resume 'swaymsg "output * dpms on"' \
	# timeout 10 'if pgrep -x swaylock; then swaymsg "output * dpms off"; fi' \
	# 	resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock -f' &

kanshi &
nm-applet --indicator &
pasystray &
blueberry-tray &

if which dropbox; then
  dropbox start
fi
