#!/bin/sh

# Script to do stuff as part of sway startup. This is mostly here because
# you can't do conditionals in sway config

LOCK_SEC=600
swayidle -w \
	timeout "$LOCK_SEC" 'swaylock' \
	timeout "$LOCK_SEC" 'swaymsg "output * dpms off"' \
	timeout 10 'if pgrep -x swaylock; then swaymsg "output * dpms off"; fi' \
	resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock' &

kanshi &
nm-applet --indicator &
pasystray &
blueberry-tray &

if which dropbox; then
  dropbox start
fi
