- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.config/:
      glob: true
      path: config/**
    ~/.gitconfig:
    ~/.profile:
      force: true
    ~/.ssh:
      glob: true
      path: ssh/**
    ~/.terminfo:
      glob: true
      path: terminfo/**
    ~/.tmux.conf:
    ~/.tmux/plugins/tpm: tmux/plugins/tpm
    ~/.vim/bundle/Vundle.vim: vim/bundle/Vundle.vim
    ~/.vim/ftplugin/python.vim: vim/ftplugin/python.vim
    ~/.vimrc:
    ~/.vimrc.local:
    ~/.vimrc.bundles:
    ~/.Xresources.d:
      glob: true
      path: Xresources.d/*
    ~/.xmodmaprc:
    ~/.xscreensaver:
    ~/.zsh:
      glob: true
      path: zsh/**
    ~/.zshrc:

- shell:
  - command: git submodule update --init --recursive
    description: Installing submodules
