#!/bin/sh

# Script to do stuff as part of sway startup. This is mostly here because
# you can't do conditionals in sway config

mkdir -p ~/.logs

export LOCK_SEC=300
swayidle -w \
	timeout "$LOCK_SEC" 'swaylock -f' \
	timeout "$LOCK_SEC" 'swaymsg "output * dpms off"' \
		resume 'swaymsg "output * dpms on"' \
	timeout 10 'if pgrep -x swaylock; then swaymsg "output * dpms off"; fi' \
		resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock -f' &

kanshi >~/.logs/kanshi.log &
nm-applet --indicator &
pasystray &
blueberry-tray &

if which dropbox; then
  dropbox start
fi
