#!/bin/sh

# Script to do stuff as part of sway startup. This is mostly here because
# you can't do conditionals in sway config

mkdir -p ~/.logs

systemctl --user import-environment SWAYSOCK \
	DISPLAY \
	I3SOCK \
	WAYLAND_DISPLAY \
	XCURSOR_SIZE \
	XCURSOR_THEME

nm-applet --indicator &
# pasystray &
# blueberry-tray &

if which dropbox; then
  dropbox start
fi
