#!/bin/sh

# Script to do stuff as part of i3 startup. This is mostly here because
# you can't do conditionals in i3 config

xsetroot -solid "#000000"

if which gnome-keyring-daemon; then
  eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
  export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
fi

# set xrandr DPI to the auto-detected DPI so that i3 looks right
xrandr --dpi 96 --output eDP1 --mode 1920x1080
setxkbmap -option 'ctrl:nocaps'

# Detect and load up autorandr screen config
autorandr -c

xscreensaver -no-splash &
nm-applet &

if which dropbox; then
  dropbox start
fi

# Restart i3 after we set DPI to get font sizes right
i3-msg restart
