#!/bin/sh

# Script to do stuff as part of i3 startup. This is mostly here because
# you can't do conditionals in i3 config

xsetroot -solid "#000000"
xrandr --dpi 160
setxkbmap -option 'ctrl:nocaps'

xscreensaver -no-splash &
nm-applet &

# Restart i3 after we set DPI to get font sizes right
i3-msg restart
