#!/bin/sh

# Script to do stuff as part of i3 startup. This is mostly here because
# you can't do conditionals in i3 config

xsetroot -solid "#000000"

setxkbmap -option 'ctrl:nocaps'

# Use xmodmap to neuter some screwy media keys
if [ -f ~/.xmodmaprc ]; then
  xmodmap ~/.xmodmaprc
fi

autorandr -c

xscreensaver -no-splash &
nm-applet &
pasystray &

if which dropbox; then
  dropbox start
fi
